name: Staging

on:
  pull_request:
    branches: [production]

jobs:
  review_code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14.x']

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache .pnpm-store
        uses: actions/cache@v2.1.5
        id: pnpm-cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install pnpm
        run: sudo npm install -g pnpm

      - name: Install Dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile
        env:
          CI: true

      - name: Linting
        run: pnpx eslint

      - name: Type checking
        run: pnpm run tsc

      - name: Build
        run: pnpm build

      - name: Deploying
        uses: amondnet/vercel-action@v20.0.0
        with:
          alias-domains: |
            {{BRANCH}}.codybrunner.dev
          github-comment: true
          github-token: ${{ github.token }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
